### ISSUE TITLE
[機能リクエスト] 他SNSへのシェアに対応してほしい

### ISSUE THREAD

**Issue by mimikun** [TaktstockJp/Kivodle#9]
現在はXとMisskeyのみですが他のSNS、例えばMastodonも欲しいです

Web Share APIで共有メニューを出すことが可能なのでそれでもいいかもしれません

**Comment by TaktstockJp** [comment]
まず前提として現状XとMisskeyのシェアボタンを置いているのは
①Xは純粋に人口が多いから
②Misskeyは自分が利用しているから
という理由であんまり深く考えていませんでした。
Mastodonへのリンク設置については、確かに分散型SNSで最もシェアが多いので前向きに検討します。
Web Share APIについては、コピーボタンの代わりに設置することを検討してみます。

**Comment by TaktstockJp** [comment]
補足的な話ですが、現状BlueSkyへのシェアボタンを設置するのは難しいと考えています。
というのも、BlueSkyへのシェアリンクとして
`https://bsky.app/intent/compose?text=(ポストしたい文字列)`
というのがあるのですが、現状では`%0A`による改行に対応していないためです。

**Comment by TaktstockJp** [comment]
Mastodonへのシェアボタン（donShare利用）を実装しました。
Web Share APIの利用は諸事情により見送っています。

**Comment by mimikun** [comment]
実装ありがとうございます

レビューコメントとしても書いたのですが `&visibility=public&localOnly=0` はおそらく不要なのでそこだけ削除いただければ大丈夫です

**Comment by TaktstockJp** [comment]
PR更新しました、指摘通り`&visibility=public&localOnly=0`だけ削除しています

**Comment by mimikun** [comment]
LGTMです
多分動くと思うのでマージお願いします
